function T_Matrix = MTM_FK(m, q)
    q_size = size(q);
    if q_size(2)~=1
        msg = sprintf('Please Set q to Vector');
        error(msg);
    elseif q_size(1)~=7
        msg = sprintf('Please length of q is %d, Please set to 7',q_size(1));
        error(msg);
    end
    q1 = q(1);
    q2 = q(2);
    q3 = q(3);
    q4 = q(4);
    q5 = q(5);
    q6 = q(6);
    q7 = q(7);
    l_arm = m.l_arm; 
    l_forearm = m.l_forearm; 
    h = m.h; 
    T_Matrix = [ sin(q7 + pi/2)*(sin(q5)*(sin(q4)*sin(q1 - pi/2) - cos(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - cos(q5)*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2))) - cos(q7 + pi/2)*(cos(q6 - pi/2)*(cos(q5)*(sin(q4)*sin(q1 - pi/2) - cos(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) + sin(q5)*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2))) + sin(q6 - pi/2)*(cos(q4)*sin(q1 - pi/2) + sin(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)))),   cos(q7 + pi/2)*(sin(q5)*(sin(q4)*sin(q1 - pi/2) - cos(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - cos(q5)*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2))) + sin(q7 + pi/2)*(cos(q6 - pi/2)*(cos(q5)*(sin(q4)*sin(q1 - pi/2) - cos(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) + sin(q5)*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2))) + sin(q6 - pi/2)*(cos(q4)*sin(q1 - pi/2) + sin(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)))), cos(q6 - pi/2)*(cos(q4)*sin(q1 - pi/2) + sin(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - sin(q6 - pi/2)*(cos(q5)*(sin(q4)*sin(q1 - pi/2) - cos(q4)*(cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) + sin(q5)*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2))), l_arm*cos(q1 - pi/2)*cos(q2 - pi/2) - h*(cos(q1 - pi/2)*cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q1 - pi/2)*cos(q3 + pi/2)*sin(q2 - pi/2)) + l_forearm*cos(q1 - pi/2)*cos(q2 - pi/2)*cos(q3 + pi/2) - l_forearm*cos(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)
 cos(q7 + pi/2)*(cos(q6 - pi/2)*(cos(q5)*(cos(q1 - pi/2)*sin(q4) + cos(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - sin(q5)*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2))) + sin(q6 - pi/2)*(cos(q4)*cos(q1 - pi/2) - sin(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)))) - sin(q7 + pi/2)*(sin(q5)*(cos(q1 - pi/2)*sin(q4) + cos(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) + cos(q5)*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2))), - cos(q7 + pi/2)*(sin(q5)*(cos(q1 - pi/2)*sin(q4) + cos(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) + cos(q5)*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2))) - sin(q7 + pi/2)*(cos(q6 - pi/2)*(cos(q5)*(cos(q1 - pi/2)*sin(q4) + cos(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - sin(q5)*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2))) + sin(q6 - pi/2)*(cos(q4)*cos(q1 - pi/2) - sin(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)))), sin(q6 - pi/2)*(cos(q5)*(cos(q1 - pi/2)*sin(q4) + cos(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))) - sin(q5)*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2))) - cos(q6 - pi/2)*(cos(q4)*cos(q1 - pi/2) - sin(q4)*(cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2))), l_arm*cos(q2 - pi/2)*sin(q1 - pi/2) - h*(cos(q2 - pi/2)*sin(q1 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q1 - pi/2)*sin(q2 - pi/2)) + l_forearm*cos(q2 - pi/2)*cos(q3 + pi/2)*sin(q1 - pi/2) - l_forearm*sin(q1 - pi/2)*sin(q2 - pi/2)*sin(q3 + pi/2)
                                                                                                                                                                                                                                        cos(q7 + pi/2)*(cos(q6 - pi/2)*(sin(q5)*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) + cos(q4)*cos(q5)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))) - sin(q4)*sin(q6 - pi/2)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))) + sin(q7 + pi/2)*(cos(q5)*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) - cos(q4)*sin(q5)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))),                                                                                                                                                                                                                                          cos(q7 + pi/2)*(cos(q5)*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) - cos(q4)*sin(q5)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))) - sin(q7 + pi/2)*(cos(q6 - pi/2)*(sin(q5)*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) + cos(q4)*cos(q5)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))) - sin(q4)*sin(q6 - pi/2)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))),                                                                                                                                                 sin(q6 - pi/2)*(sin(q5)*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) + cos(q4)*cos(q5)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2))) + cos(q6 - pi/2)*sin(q4)*(cos(q2 - pi/2)*sin(q3 + pi/2) + cos(q3 + pi/2)*sin(q2 - pi/2)),                                                                            h*(cos(q2 - pi/2)*cos(q3 + pi/2) - sin(q2 - pi/2)*sin(q3 + pi/2)) + l_arm*sin(q2 - pi/2) + l_forearm*cos(q2 - pi/2)*sin(q3 + pi/2) + l_forearm*cos(q3 + pi/2)*sin(q2 - pi/2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                       1];
 
end